/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountSettingsSection: typeof import('./src/components/user/settings/sections/AccountSettingsSection.vue')['default']
    AppFooter: typeof import('./src/components/common/AppFooter.vue')['default']
    AppNavbar: typeof import('./src/components/common/AppNavbar.vue')['default']
    AppRouteTransition: typeof import('./src/components/common/AppRouteTransition.vue')['default']
    AppToast: typeof import('./src/components/common/AppToast.vue')['default']
    AuthCard: typeof import('./src/components/auth/AuthCard.vue')['default']
    BasicProfileSection: typeof import('./src/components/user/settings/sections/BasicProfileSection.vue')['default']
    DataManagementSection: typeof import('./src/components/user/settings/sections/DataManagementSection.vue')['default']
    FloatingActionButton: typeof import('./src/components/common/FloatingActionButton.vue')['default']
    HeroSection: typeof import('./src/components/user/HeroSection.vue')['default']
    MessageSettingsSection: typeof import('./src/components/user/settings/sections/MessageSettingsSection.vue')['default']
    PreferenceSettingsSection: typeof import('./src/components/user/settings/sections/PreferenceSettingsSection.vue')['default']
    PreviewSandbox: typeof import('./src/components/auth/PreviewSandbox.vue')['default']
    ProfileContributionSection: typeof import('./src/components/user/profile/ProfileContributionSection.vue')['default']
    ProfileHeatmapSection: typeof import('./src/components/user/profile/ProfileHeatmapSection.vue')['default']
    ProfileHeroSection: typeof import('./src/components/user/profile/ProfileHeroSection.vue')['default']
    ProfileProjectGridSection: typeof import('./src/components/user/profile/ProfileProjectGridSection.vue')['default']
    ProfileSidebarCard: typeof import('./src/components/user/profile/ProfileSidebarCard.vue')['default']
    ProfileSiteGridSection: typeof import('./src/components/user/profile/ProfileSiteGridSection.vue')['default']
    ProfileSkillsSection: typeof import('./src/components/user/profile/ProfileSkillsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDataSection: typeof import('./src/components/user/settings/SettingsDataSection.vue')['default']
    SettingsNotificationsSection: typeof import('./src/components/user/settings/SettingsNotificationsSection.vue')['default']
    SettingsPreferencesSection: typeof import('./src/components/user/settings/SettingsPreferencesSection.vue')['default']
    SettingsProfileSection: typeof import('./src/components/user/settings/SettingsProfileSection.vue')['default']
    SettingsSecuritySection: typeof import('./src/components/user/settings/SettingsSecuritySection.vue')['default']
    SettingsSidebar: typeof import('./src/components/user/settings/SettingsSidebar.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UContainer: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USkeleton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    WebsiteCard: typeof import('./src/components/user/WebsiteCard.vue')['default']
    WebsiteFilter: typeof import('./src/components/user/WebsiteFilter.vue')['default']
    WebsiteGrid: typeof import('./src/components/user/WebsiteGrid.vue')['default']
  }
}

// For TSX support
declare global {
  const AccountSettingsSection: typeof import('./src/components/user/settings/sections/AccountSettingsSection.vue')['default']
  const AppFooter: typeof import('./src/components/common/AppFooter.vue')['default']
  const AppNavbar: typeof import('./src/components/common/AppNavbar.vue')['default']
  const AppRouteTransition: typeof import('./src/components/common/AppRouteTransition.vue')['default']
  const AppToast: typeof import('./src/components/common/AppToast.vue')['default']
  const AuthCard: typeof import('./src/components/auth/AuthCard.vue')['default']
  const BasicProfileSection: typeof import('./src/components/user/settings/sections/BasicProfileSection.vue')['default']
  const DataManagementSection: typeof import('./src/components/user/settings/sections/DataManagementSection.vue')['default']
  const FloatingActionButton: typeof import('./src/components/common/FloatingActionButton.vue')['default']
  const HeroSection: typeof import('./src/components/user/HeroSection.vue')['default']
  const MessageSettingsSection: typeof import('./src/components/user/settings/sections/MessageSettingsSection.vue')['default']
  const PreferenceSettingsSection: typeof import('./src/components/user/settings/sections/PreferenceSettingsSection.vue')['default']
  const PreviewSandbox: typeof import('./src/components/auth/PreviewSandbox.vue')['default']
  const ProfileContributionSection: typeof import('./src/components/user/profile/ProfileContributionSection.vue')['default']
  const ProfileHeatmapSection: typeof import('./src/components/user/profile/ProfileHeatmapSection.vue')['default']
  const ProfileHeroSection: typeof import('./src/components/user/profile/ProfileHeroSection.vue')['default']
  const ProfileProjectGridSection: typeof import('./src/components/user/profile/ProfileProjectGridSection.vue')['default']
  const ProfileSidebarCard: typeof import('./src/components/user/profile/ProfileSidebarCard.vue')['default']
  const ProfileSiteGridSection: typeof import('./src/components/user/profile/ProfileSiteGridSection.vue')['default']
  const ProfileSkillsSection: typeof import('./src/components/user/profile/ProfileSkillsSection.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SettingsDataSection: typeof import('./src/components/user/settings/SettingsDataSection.vue')['default']
  const SettingsNotificationsSection: typeof import('./src/components/user/settings/SettingsNotificationsSection.vue')['default']
  const SettingsPreferencesSection: typeof import('./src/components/user/settings/SettingsPreferencesSection.vue')['default']
  const SettingsProfileSection: typeof import('./src/components/user/settings/SettingsProfileSection.vue')['default']
  const SettingsSecuritySection: typeof import('./src/components/user/settings/SettingsSecuritySection.vue')['default']
  const SettingsSidebar: typeof import('./src/components/user/settings/SettingsSidebar.vue')['default']
  const UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  const UAvatar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
  const UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
  const UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
  const UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
  const UContainer: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
  const UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
  const UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
  const USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
  const USkeleton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
  const UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  const WebsiteCard: typeof import('./src/components/user/WebsiteCard.vue')['default']
  const WebsiteFilter: typeof import('./src/components/user/WebsiteFilter.vue')['default']
  const WebsiteGrid: typeof import('./src/components/user/WebsiteGrid.vue')['default']
}