<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>



    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.5</version>
        <relativePath/>
    </parent>

    <groupId>com.yyyouth</groupId>
    <artifactId>computer-favorites-back</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <modules>
        <module>cf-web</module>
        <module>cf-common</module>
        <module>cf-service</module>
        <module>cf-core</module>
        <module>cf-model</module>
    </modules>

    <properties>
        <cf.version>1.0.0</cf.version>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <minio.version>7.1.0</minio.version>
        <mybatis-plus.version>3.5.14</mybatis-plus.version>
        <mysql.version>8.2.0</mysql.version>
        <knife4j.version>4.4.0</knife4j.version>
        <satoken.version>1.44.0</satoken.version>
        <hutool.version>5.8.38</hutool.version>
        <druid.version>1.2.23</druid.version>
        <redisson.version>3.45.0</redisson.version>
        <validator.version>3.4.12</validator.version>
        <spring-ai.version>1.0.0</spring-ai.version>
        <lombok.version>1.18.38</lombok.version>
        <sensitive-word.version>0.29.3</sensitive-word.version>
    </properties>

    <dependencyManagement>


        <dependencies>

            <!-- 敏感词检测框架 -->
            <dependency>
                <groupId>com.github.houbb</groupId>
                <artifactId>sensitive-word</artifactId>
                <version>${sensitive-word.version}</version>
            </dependency>

       <!--       spring ai-->
<!--                <dependency>-->
<!--                    <groupId>org.springframework.ai</groupId>-->
<!--                    <artifactId>spring-ai-bom</artifactId>-->
<!--                    <version>${spring-ai.version}</version>-->
<!--                    <type>pom</type>-->
<!--                    <scope>import</scope>-->
<!--                </dependency>-->

            <!-- minio -->
            <dependency>
                <groupId>io.minio</groupId>
                <artifactId>minio</artifactId>
                <version>${minio.version}</version>
                <scope>compile</scope>
            </dependency>


            <!-- redisson分布式锁-->
            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson</artifactId>
                <version>${redisson.version}</version>
            </dependency>


            <!-- 阿里数据库连接池 -->
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-3-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>


            <!-- mybatis-plus -->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>

            <!--      mysql-->
            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>${mysql.version}</version>
            </dependency>

            <!-- Sa-Token 权限认证，在线文档：https://sa-token.cc -->
            <dependency>
                <groupId>cn.dev33</groupId>
                <artifactId>sa-token-spring-boot3-starter</artifactId>
                <version>${satoken.version}</version>
            </dependency>

            <!-- Sa-Token 整合 jwt -->
            <dependency>
                <groupId>cn.dev33</groupId>
                <artifactId>sa-token-jwt</artifactId>
                <version>${satoken.version}</version>
            </dependency>

            <!--            hutool 包-->
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>


<!--            服务和中间件模块-->
            <dependency>
                <groupId>com.yyyouth</groupId>
                <artifactId>cf-service</artifactId>
                <version>${cf.version}</version>
            </dependency>

<!--            API模块-->
            <dependency>
                <groupId>com.yyyouth</groupId>
                <artifactId>cf-web</artifactId>
                <version>${cf.version}</version>
            </dependency>


            <!--      启动器模块      -->
            <dependency>
                <groupId>com.yyyouth</groupId>
                <artifactId>cf-core</artifactId>
                <version>${cf.version}</version>
            </dependency>


            <!--      通用工具模块      -->
            <dependency>
                <groupId>com.yyyouth</groupId>
                <artifactId>cf-common</artifactId>
                <version>${cf.version}</version>
            </dependency>

            <!--      数据模型模块      -->
            <dependency>
                <groupId>com.yyyouth</groupId>
                <artifactId>cf-model</artifactId>
                <version>${cf.version}</version>
            </dependency>
        </dependencies>

    </dependencyManagement>

    <dependencies>
        <!-- lombok依赖-->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>

        <!-- knife4j -->
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi2-spring-boot-starter</artifactId>
            <version>4.4.0</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>


    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <parameters>true</parameters>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
